# Generated by Django 5.1.2 on 2024-10-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logotype', models.ImageField(upload_to='images')),
                ('logotype_footer', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Unknown', max_length=50)),
                ('publisher', models.CharField(default='Unknown', max_length=50)),
                ('comment', models.TextField(default='Something')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
