# Generated by Django 5.1.2 on 2024-10-16 08:36

import dynamic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0008_alter_socialmedia_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logotype',
            name='logotype',
        ),
        migrations.RemoveField(
            model_name='logotype',
            name='logotype_footer',
        ),
        migrations.AddField(
            model_name='logotype',
            name='logotype_in_footer',
            field=models.FileField(default=1, upload_to='images', validators=[dynamic.models.FileExtensionValidator()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logotype',
            name='logotype_in_header',
            field=models.FileField(default=2, upload_to='images', validators=[dynamic.models.FileExtensionValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.FileField(upload_to='images', validators=[dynamic.models.FileExtensionValidator()]),
        ),
    ]
