# Generated by Django 5.1.2 on 2024-10-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_helplist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('take_care', models.CharField(max_length=15)),
            ],
        ),
    ]
