# Generated by Django 5.1.2 on 2024-10-16 08:26

import dynamic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0007_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='image',
            field=models.FileField(upload_to='images', validators=[dynamic.models.FileExtensionValidator()]),
        ),
    ]
