# Generated by Django 5.1.2 on 2024-10-16 09:02

import dynamic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0009_remove_logotype_logotype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_logo', models.FileField(upload_to='images', validators=[dynamic.models.FileExtensionValidator()])),
                ('result', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('product', models.CharField(max_length=20)),
                ('platform', models.CharField(max_length=15)),
                ('card_in_slider', models.FileField(upload_to='images', validators=[dynamic.models.FileExtensionValidator()])),
            ],
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='date',
        ),
    ]
